#!/bin/bash -e
# vim: noet

# This prerm script will remove the user and group for the package if it exists.
# But it will not remove the user's home directory.

ONESSH_USER=onessh-chad
ONESSH_GROUP=onessh

_remove() {
	# Remove the user if it exists
	if getent passwd $ONESSH_USER >/dev/null; then
		deluser --system $ONESSH_USER >/dev/null
	fi

	# Remove the group if it exists
	if getent group $ONESSH_GROUP >/dev/null; then
		delgroup --system $ONESSH_GROUP >/dev/null
	fi

	echo "Removed user $ONESSH_USER and group $ONESSH_GROUP"
	echo "The home directory \"$ONESSH_HOME\" is kept, \
		please remove it manually if you think it's no longer needed."
}

case "$1" in
	remove|deconfigure)
		_remove
		;;
	upgrade|failed-upgrade)
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac
