# Build the debian package and create a release when a tag is pushed

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build debian package
        uses: jtdor/build-deb-action@v1
        with:
          artifacts-dir: debian/artifacts
          buildpackage-opts: --no-sign -b
      - name: Rename debian package
        run: sudo cp debian/artifacts/*.deb onessh.deb
      - name: generate onesshup.sh
        run: |
          DEB_URL="${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/onessh.deb" envsubst '$DEB_URL' < onesshup.sh.template > onesshup.sh
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            onessh.deb
            onesshup.sh
          tag_name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
            ---
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
