# Build the debian package and create a release when a tag is pushed

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build debian package
        run: poetry run python setup.py --command-packages=stdeb.command bdist_deb
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.deb
          tag_name: ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            ---
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
